### ISSUE TITLE
Integration doesn't start since few days...

### ISSUE THREAD

**Issue by Loic691** [maciej-or/hikvision_next#187] opened 2024-07-16 07:57 UTC
Hi
My integration doesn't start since few days...
I'm not sure of the cause : 
- Update HA to 2024.7 version
- update HIK cam to V5.7.17 build 240606 
- update of the HACS hikvision integration*

I'm not sure but I think this issue is since the update of HIKVISION integration in HACS.
My camera are DS-2CD2146G2-ISU and DS-2CD2147G2-SU

Here's the error log and the two error for each cam

```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:586
S'est produit pour la première fois: 09:56:19 (4 occurrences)
Dernier enregistrement: 09:56:19

Error setting up entry Caméra Terrasse for binary_sensor
Error setting up entry Caméra Terrasse for camera
Error setting up entry Caméra Terrasse for sensor
Error setting up entry Caméra Terrasse for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 231, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry Caméra Terrasse (5c4bca7bebca544a3c796e334ba0627d) for hikvision_next.binary_sensor has already been setup!
```

and

```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:586
S'est produit pour la première fois: 09:56:19 (1 occurrences)
Dernier enregistrement: 09:56:19

Error setting up entry Caméra Terrasse for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/__init__.py", line 93, in async_setup_entry
    refresh_disabled_entities_in_registry(hass, isapi)
  File "/config/custom_components/hikvision_next/__init__.py", line 181, in refresh_disabled_entities_in_registry
    update_entity(event, SWITCH_ENTITY_ID_FORMAT)
  File "/config/custom_components/hikvision_next/__init__.py", line 170, in update_entity
    if entity.disabled != event.disabled:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'disabled'
```

**Comment by maciej-or** [comment] 2024-07-16 08:25
did you rename Entities ID? Try to remove device and add again.
If error wont gone please downgrade to v1.0.15 https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.15, and let me know.

**Comment by maciej-or** [comment] 2024-07-16 08:55
It looks some of binary sensors has renamed entity ID or was not added to the entity registry. I would remove all cameras to make sure.
The cause is in new version so downgrade should fix the issue. Do you remember to restart HA after downgrade?
I'm marking this as a bug and it will be fixed soon.

**Comment by Loic691** [comment] 2024-07-16 09:10
Thanks
So this is ok with 1.0.15.
I have to reboot HA after remove hikvision device from integration.
Then after reboot, recreate them...

**Closed** 2024-07-18 18:23 UTC
Labels: bug
