### ISSUE TITLE
PIR alarm DS-2CD2420F-I

### ISSUE THREAD

**Issue by TokarevSergey** [maciej-or/hikvision_next#122] opened 2023-10-03 19:38 UTC
Good evening.  Tell me if it is possible to deliver a PIR alarm switch.
Thank you.
Camera DS
![Screenshot_20231003_223559_Chrome](https://github.com/maciej-or/hikvision_next/assets/98225056/888d9f2f-0a33-442c-a447-7ddbcce1d01c)
-2CD2420F-I.

**Comment by maciej-or** [comment] 2023-11-16 22:24
Duplicate of #1 

@TokarevSergey for the future please change language to English before taking screenshots.

**Comment by maciej-or** [comment] 2024-08-09 17:16
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.17

**Closed by maciej-or** 2024-08-09 17:16 UTC
Labels: duplicate
